version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: clms_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Change this to something more secure
      MYSQL_DATABASE: clms_db
      MYSQL_USER: clms_user
      MYSQL_PASSWORD: clms_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: