name: CI Workflow

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/ci_workflow.yml'

env:
  DOCKER_BUILDKIT: 1

jobs:
  detect-changes:
    name: Detect changed directories
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.check-frontend.outputs.changed }}
      backend-changed: ${{ steps.check-backend.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for frontend changes
        id: check-frontend
        run: |
          echo "Checking for frontend changes..."
          changes=$(git diff --name-only HEAD~1 HEAD | grep -c '^frontend/') || true
          if [ "$changes" -gt 0 ]; then
            echo "frontend-changed=true" >> $GITHUB_OUTPUT
          else
            echo "frontend-changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for backend changes
        id: check-backend
        run: |
          echo "Checking for backend changes..."
          changes=$(git diff --name-only HEAD~1 HEAD | grep -c '^backend/') || true
          if [ "$changes" -gt 0 ]; then
            echo "backend-changed=true" >> $GITHUB_OUTPUT
          else
            echo "backend-changed=false" >> $GITHUB_OUTPUT
          fi

  build-frontend:
    name: Build Frontend Docker Image
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-changed == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Build Frontend Docker image (test only)
        working-directory: ./frontend
        run: |
          docker build \
            --tag frontend:pr-${GITHUB_PR_RUN_ID} \
            .

  build-backend:
    name: Build Backend Docker Image
    needs: detect-changes
    if: needs.detect-changes.outputs.backend-changed == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Build Backend Docker image (test only)
        working-directory: ./backend
        run: |
          docker build \
            --tag backend:pr-${GITHUB_PR_RUN_ID} \
            .