name: Docker Build CI

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/docker-build.yml'

env:
  DOCKER_BUILDKIT: 1

jobs:
  detect-changes:
    name: Detect changed directories
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.check-frontend.outputs.changed }}
      backend-changed: ${{ steps.check-backend.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for frontend changes
        id: check-frontend
        run: |
          echo "Checking for frontend changes..."
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            changes=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -c '^frontend/') || true
          else
            changes=$(git diff --name-only HEAD~1 HEAD | grep -c '^frontend/') || true
          fi
          echo "changed=$changes" >> $GITHUB_STATE
          if [ "$changes" -gt 0 ]; then
            echo "frontend-changed=true" >> $GITHUB_OUTPUT
          else
            echo "frontend-changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for backend changes
        id: check-backend
        run: |
          echo "Checking for backend changes..."
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            changes=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -c '^backend/') || true
          else
            changes=$(git diff --name-only HEAD~1 HEAD | grep -c '^backend/') || true
          fi
          echo "changed=$changes" >> $GITHUB_STATE
          if [ "$changes" -gt 0 ]; then
            echo "backend-changed=true" >> $GITHUB_OUTPUT
          else
            echo "backend-changed=false" >> $GITHUB_OUTPUT
          fi

  build-frontend:
    name: Build Frontend Docker Image
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-changed == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        if: github.event_name == 'push' && secrets.DOCKER_HUB_USERNAME && secrets.DOCKER_HUB_TOKEN
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build Frontend Docker image
        working-directory: ./frontend
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            docker build --tag frontend:pr-${{ github.event.number }} .
          else
            docker build \
              --tag frontend:${{ github.sha }} \
              --tag frontend:latest \
              .
          fi
            
      - name: Push Frontend Docker image
        if: github.event_name == 'push' && secrets.DOCKER_HUB_USERNAME && secrets.DOCKER_HUB_TOKEN
        run: |
          docker tag frontend:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }}
          docker tag frontend:latest ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

  build-backend:
    name: Build Backend Docker Image
    needs: detect-changes
    if: needs.detect-changes.outputs.backend-changed == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        if: github.event_name == 'push' && secrets.DOCKER_HUB_USERNAME && secrets.DOCKER_HUB_TOKEN
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build Backend Docker image
        working-directory: ./backend
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            docker build --tag backend:pr-${{ github.event.number }} .
          else
            docker build \
              --tag backend:${{ github.sha }} \
              --tag backend:latest \
              .
          fi
            
      - name: Push Backend Docker image
        if: github.event_name == 'push' && secrets.DOCKER_HUB_USERNAME && secrets.DOCKER_HUB_TOKEN
        run: |
          docker tag backend:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/backend:${{ github.sha }}
          docker tag backend:latest ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest