name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_BUILDKIT: 1
  DOCKER_HUB_REPO: your-dockerhub-username/repo-name  # Update this

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      build-frontend: ${{ steps.check-dirs.outputs.frontend }}
      build-backend: ${{ steps.check-dirs.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check changed directories
        id: check-dirs
        run: |
          echo "Checking changed files..."
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          else
            changed_files=$(git diff --name-only HEAD~1 HEAD)
          fi
          
          echo "Changed files:"
          echo "$changed_files"
          
          if echo "$changed_files" | grep -q '^frontend/'; then
            echo "frontend=true" >> $GITHUB_OUTPUT
          else
            echo "frontend=false" >> $GITHUB_OUTPUT
          fi
          
          if echo "$changed_files" | grep -q '^backend/'; then
            echo "backend=true" >> $GITHUB_OUTPUT
          else
            echo "backend=false" >> $GITHUB_OUTPUT
          fi

  build-and-push:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [frontend, backend]
        include:
          - component: frontend
            directory: frontend
          - component: backend
            directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Verify directory exists
        id: check-dir
        run: |
          if [ -d "${{ matrix.directory }}" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.check-dir.outputs.exists == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: steps.check-dir.outputs.exists == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        if: needs.detect-changes.outputs.build-${{ matrix.component }} == 'true' && steps.check-dir.outputs.exists == 'true'
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            TAG=pr-${{ github.event.number }}
          else
            TAG=${{ github.sha }}
          fi
          
          cd ${{ matrix.directory }}
          docker build -t ${{ env.DOCKER_HUB_REPO }}-${{ matrix.component }}:$TAG .
          docker push ${{ env.DOCKER_HUB_REPO }}-${{ matrix.component }}:$TAG
          
          if [ "${{ github.event_name }}" = "push" ]; then
            docker tag ${{ env.DOCKER_HUB_REPO }}-${{ matrix.component }}:$TAG ${{ env.DOCKER_HUB_REPO }}-${{ matrix.component }}:latest
            docker push ${{ env.DOCKER_HUB_REPO }}-${{ matrix.component }}:latest
          fi