name: Build Docker Images

on:
  push:
    branches: [ main ]  # Change to your default branch if different
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/docker-build.yml'  # Trigger if workflow file changes

env:
  DOCKER_BUILDKIT: 1  # Enable Docker BuildKit for faster builds

jobs:
  detect-changes:
    name: Detect changed directories
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.check-frontend.outputs.changed }}
      backend-changed: ${{ steps.check-backend.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Needed to compare changes

      - name: Check for frontend changes
        id: check-frontend
        run: |
          echo "Checking for frontend changes..."
          changes=$(git diff --name-only HEAD~1 HEAD | grep -c '^frontend/') || true
          if [ "$changes" -gt 0 ]; then
            echo "frontend-changed=true" >> $GITHUB_OUTPUT
          else
            echo "frontend-changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for backend changes
        id: check-backend
        run: |
          echo "Checking for backend changes..."
          changes=$(git diff --name-only HEAD~1 HEAD | grep -c '^backend/') || true
          if [ "$changes" -gt 0 ]; then
            echo "backend-changed=true" >> $GITHUB_OUTPUT
          else
            echo "backend-changed=false" >> $GITHUB_OUTPUT
          fi

  build-frontend:
    name: Build Frontend Docker Image
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-changed == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub (optional)
        if: env.DOCKER_HUB_USERNAME && env.DOCKER_HUB_TOKEN
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build Frontend Docker image
        working-directory: ./frontend
        run: |
          docker build \
            --tag frontend:${GITHUB_SHA::7} \
            --tag frontend:latest \
            .
            
      - name: Push Frontend Docker image (optional)
        if: env.DOCKER_HUB_USERNAME && env.DOCKER_HUB_TOKEN
        run: |
          docker tag frontend:${GITHUB_SHA::7} ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${GITHUB_SHA::7}
          docker tag frontend:latest ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

  build-backend:
    name: Build Backend Docker Image
    needs: detect-changes
    if: needs.detect-changes.outputs.backend-changed == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub (optional)
        if: env.DOCKER_HUB_USERNAME && env.DOCKER_HUB_TOKEN
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build Backend Docker image
        working-directory: ./backend
        run: |
          docker build \
            --tag backend:${GITHUB_SHA::7} \
            --tag backend:latest \
            .
            
      - name: Push Backend Docker image (optional)
        if: env.DOCKER_HUB_USERNAME && env.DOCKER_HUB_TOKEN
        run: |
          docker tag backend:${GITHUB_SHA::7} ${{ secrets.DOCKER_HUB_USERNAME }}/backend:${GITHUB_SHA::7}
          docker tag backend:latest ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest